name: DemoHambleServer
host: 127.0.0.1
post: 6177
tcp_version: tcp4 # tcp or tcp4 or tcp6
max_conn: 12000
max_packet_size: 4096
worker_pool_size: 10
max_msg_chan_len: 1024
max_heartbeat_time: 10
log_file_name: hamble.log